# Generated by Django 5.0.3 on 2024-10-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biz_haqimizda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('haqida', models.CharField(max_length=150)),
                ('rasm', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
