# Generated by Django 5.0.3 on 2024-10-22 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_biz_haqimizda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
            ],
        ),
    ]
