# Generated by Django 5.0.3 on 2024-10-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_biz_a'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimular_rasm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Testimullar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('haqida', models.CharField(max_length=150)),
                ('ismi', models.CharField(max_length=50)),
            ],
        ),
    ]
